### ISSUE TITLE
Can't resolve './buffer' after upgrading to 2.2.2

### ISSUE THREAD

**Issue by petriichuk** [taoyuan/mutable-buffer#7]
ERROR in ./node_modules/mutable-buffer/dist/mutable-buffer.js
Module not found: Error: Can't resolve './buffer' in '/opt/atlassian/pipelines/agent/build/node_modules/mutable-buffer/dist'
 @ ./node_modules/mutable-buffer/dist/mutable-buffer.js 4:17-36
 @ ./node_modules/mutable-buffer/dist/index.js

Rolled back to 2.2.1, working fine

**Comment by taoyuan** [comment]
Just published `2.2.3` to fix `tslib` missing issue. 

But I can't reproduce the problem you said. Can you test it with `2.2.3` to see whether the problem still exists. If it still exists, can you tell the operating system, node version, and steps to reproduce it.

**Comment by petriichuk** [comment]
I think I got confused 2.2.1 vs 2.1.1. 
I had "mutable-buffer": "^2.1.1", and it worked yesterday, they today it stopped. I changed to exact version "mutable-buffer": "2.1.1" - and it works

if you need I can test later and provide more details

**Comment by taoyuan** [comment]
I made this updates mainly to match the current version API of `Buffer`, and by the way added 3 methods to remove (trim) the first and last null bytes according to [an issue](https://github.com/taoyuan/mutable-buffer/issues/1).

The new version `2.2.x` keeps same API with `2.1.x` basically except that has removed `noAssert` optional parameter to make it consistent with the newest version API of `Buffer`.

The problem you are met is probably caused by the missing `tslib` package dependency. Because of some packages in `devDependencies` contain dependencies of `tslib`, this problem was not discovered in time during unit testing.

Please upgrade to `2.2.3` if you can, and also feedback the results. Thanks.

**Comment by taoyuan** [comment]
I have reproduced this issue in browser environment. The browser support need a better way. I removed the imperfect browser support implementation and published `2.2.5`, it should work as original.

I'm sorry to trouble you.

**Comment by taoyuan** [comment]
I found out where the problem was and fixed it. I have tested it in a web project. The unit test of the browser environment should be added later.

**Comment by taoyuan** [comment]
If this issue is still in version `2.2.5`, please reopen this issue. Thanks!
